apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-data
  namespace: gitlab
spec:
  replicas: 1
  selector:
    name: redis-data
  template:
    metadata:
      name: redis-data
      labels:
        name: redis-data
    spec:
      containers:
      - name: redis-data
        image: redis:5.0.9
        ports:
        - name: redis
          containerPort: 6379
        volumeMounts:
        - mountPath: /var/lib/redis
          name: data
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          timeoutSeconds: 1
      volumes:
      - name: data
        emptyDir: {}
